### ISSUE TITLE
java.lang.RuntimeException: Failed to call observer method

### ISSUE THREAD

**Issue by nikhilsutar123** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#14]
Getting this error after implementing click listener for RecyclerView. When clicked on any sleep quality image, the app force closes.

`Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter item
        at com.example.android.trackmysleepquality.BindingUtilKt.setSleepImage(Unknown Source:7)
        at com.example.android.trackmysleepquality.databinding.FragmentSleepDetailBindingImpl.executeBindings(FragmentSleepDetailBindingImpl.java:145)`

**Comment by gq9000** [comment]
I changed the setSleepImage function in BindingUtils.kt to accept a null value like the other functions in that file. I don't know if that's what you're supposed to do but it works now.

@BindingAdapter("sleepImage")
fun ImageView.setSleepImage(item: **SleepNight?**) {
   **item?.let{**
        setImageResource(when (item.sleepQuality) {
            0 -> R.drawable.ic_sleep_0
            1 -> R.drawable.ic_sleep_1
            2 -> R.drawable.ic_sleep_2
            3 -> R.drawable.ic_sleep_3
            4 -> R.drawable.ic_sleep_4
            5 -> R.drawable.ic_sleep_5
            else -> R.drawable.ic_sleep_active
        })
    **}**
}

**Comment by zagoli** [comment]
Same issue, commented image in sleep detail and now it works

**Comment by Tibor42** [comment]
Same issue and gq9000 solution worked :-)

**Comment by sunitasavaliya** [comment]
Same issue and gq9000 solution worked :-)

**Comment by dhananjaysharma1** [comment]
I have added an observer on the SleepDetailFragment.kt to bind the views together as a work around it seems to work as intended. 

sleepDetailViewModel.night.observe(viewLifecycleOwner, Observer {

            binding.qualityImage.setSleepImage(it)
            binding.qualityString.sleepQualityString(it)
            binding.sleepLength.setSleepDurationFormatted(it)

        })
