### ISSUE TITLE
RecycledView, item list change animation

### ISSUE THREAD

**Issue by alfabravo2013** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#15]
After introducing data binding to the application (RecycledView with LinearLayoutManage), animation of adding new items to the list has a strange behavior. It works properly until the list expands beyond the height of the screen, and after that adding new items does not make the list scroll down.

Update: the same is with GridLayout. It seems that when the list of items it too big to fit the screen, animation ignores the constraints of the RecycledView and plays as if there is no buttons on the screen and the RecycleView fills the entire space of the ConstraintLayout.

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
