### ISSUE TITLE
BottomNavigation resets AppStats

### ISSUE THREAD

**Issue by Dannark** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#18]
Hi guys,
This is a problem I'm facing for a couple of days now but I couldn't find a good solution so far.

**The problem**
I've implemented a bottom navigation bar in my Main activity, I have 3 fragments and they are all using viewModels to save the app state but even doing that whenever I switch between fragments, my recycler views get reset to the top of the list, and that is not the behavior I wish.

What do you guys recommend to me?

Thanks!

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
