### ISSUE TITLE
Improvement on increasing header item span size using spanSizeLookup

### ISSUE THREAD

**Issue by OganBelema** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#2]
<img width="488" alt="andfun-kotlin-sleep-tracker-with-recyclerview  ~:StudioProjects:andfun-kotlin-sleep-tracker-with-recyclerview  -  :app:src:ma… 2019-08-19 23-34-44" src="https://user-images.githubusercontent.com/20526391/63304178-16a3bf80-c2da-11e9-8d8d-eba8f0a48a31.png">
<img width="559" alt="andfun-kotlin-sleep-tracker-with-recyclerview  ~:StudioProjects:andfun-kotlin-sleep-tracker-with-recyclerview  -  :app:src:ma… 2019-08-19 23-35-18" src="https://user-images.githubusercontent.com/20526391/63304179-16a3bf80-c2da-11e9-9276-58ccaafe8459.png">

**Comment by SudKul** [comment]
@OganBelema 
Can you raise a PR instead? Thanks.
