### ISSUE TITLE
When using DiffUtils, I noticed that the recycler view does not auto scroll to top anymore.

### ISSUE THREAD

**Issue by nishatoma** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#25]
It works initially, but when you add a certain number of elements that go off the recycler view height, and then you click "start," it will add a new item to the list, but  you would have to scroll up to see it! I tried to force the recyclerview to scroll to position 0 manually in:

`sleepTrackerViewModel.nights.observe(viewLifecycleOwner, Observer { list ->
            list?.let {
                sleepNightAdapter.submitList(list)
                binding.rvSleepList.scrollToPosition(0)
            }
        })`

But this does not work. Any suggestions?

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
