### ISSUE TITLE
DiffUtil.ItemCallback areContentsTheSame() shows linter warning when comparing sealed classes

### ISSUE THREAD

**Issue by rektdeckard** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#3]
It looks like this issue [will be patched](https://issuetracker.google.com/issues/132234925) in Android Studio 3.6, but the linter throws a warning when checking instance equality of two subclasses of a sealed class. This pops up in `DiffUtil.ItemCallback` method `areContentsTheSame()` in Step 13 of the lesson. 

Thought it might be good to mention in the instructor notes, or add `@SuppressLint("DiffUtilEquals")`, since I though the solution was to override `DataItem.equals()`.

**Comment by maxim-yudin** [comment]
It's not the right solution. There's the wrong methods realization

**Comment by maxim-yudin** [comment]
This is right solution - https://github.com/udacity/andfun-kotlin-sleep-tracker-with-recyclerview/pull/5

**Comment by SudKul** [comment]
Stale discussion.
