### ISSUE TITLE
Unresolved reference TextItemViewHolder

### ISSUE THREAD

**Issue by stef-ang** [udacity/andfun-kotlin-sleep-tracker-with-recyclerview#8]
I don't use this repository, instead I use the previous project (https://github.com/udacity/andfun-kotlin-sleep-tracker) to continue this course, but I can't get `TextItemViewHolder` even though I've copied  `text_item_view.xml`. What do I need to do?

**Comment by stef-ang** [comment]
ohh I found it at UriUtils.kt https://github.com/udacity/andfun-kotlin-sleep-tracker-with-recyclerview/blob/master/app/src/main/java/com/example/android/trackmysleepquality/Util.kt
CodeLabs shows more detail https://codelabs.developers.google.com/codelabs/kotlin-android-training-recyclerview-fundamentals/#3

**Comment by AditiDeshpande** [comment]
I copied class into Utils still I am getting error unresolved. Why is it so?

**Comment by AditiDeshpande** [comment]
Ohh my I added class inside last function's body.. Horribly silly mistake... anyways fixed it.. Errors gone.. :) :)
